Homework1
made-ml-in-prod-2021/akoshel pull request #2
Opened 2021-05-01 08:43 UTC by akoshel

Все что написано ниже есть в README (там удобнее читать)
Данные для модели были взяты отсюда https://www.kaggle.com/ronitf/heart-disease-uci
Для обработки данных построен пайплайн:

Для числовых признаков применена нормализация
Для категориальных признаков OneHotEncoding
Для классификации построены следующие модели:

Logistic Regression
Random Forest Classifier

Самоанализ
-2)) done
-1)) done
0)) done
1)) Датасет простой, в целом для его изучения было достаточно отчета из pandas_profiling
2)) done
3)) done
4)) done
5)) done. Использовано hypothesis
6)) done. 2 конфига для лр и рф
7)) done
8)) не сделано, тк. не знаю как сдампить кастомый трансформер для последующей валидации
9)) done
10)) done
11)) пока что -
12)) пока что -
13)) done

2021-05-01 09:05 UTC, Mikhail-M commented
Проставьте баллы в самоанализе плз

2021-05-01 09:14 UTC, Mikhail-M commented
по поводу 9, попробуйте этот материал
https://rebeccabilbro.github.io/module-main-has-no-attribute/

2021-05-01 11:59 UTC, munraito reviewed
Привет, по коду и запуску все нормально, кроме одного нюанса: если не создана папка models, то выдает ошибку при попытке дампа pickle-файла.
По самооценке согласен, выходит 28 баллов.

2021-05-03 14:35 UTC, Mikhail-M commented
Кстати, предполагается, что в этом репозитории будут так же жить и другие домашки, так что все это еще в одну папку поместите

2021-05-04 08:42 UTC, Mikhail-M requested changes
Доделать пункт 9 про трансформер и перенести все в папку mlproject, потому что будут еще домашки

2021-05-04 19:12 UTC, akoshel commented
Все таки доделал кастомный трансформер :)
И все перенес в папку homework1

2021-05-05 08:18 UTC, Mikhail-M requested changes

2021-05-05 08:18 UTC, Mikhail-M commented on homework1/tests/test_data.py
> +def test_classifier(init_data, train_params):
стоит тестики вынести в разные файлы

test_model, test_pipeline и тд

я вот был немного смущен тем, что в test_data все это оказалось

2021-05-05 08:18 UTC, Mikhail-M commented on homework1/tests/test_data.py
> +    pipeline = DataProcessingPipeline(train_params.feature_params.categorical_features,
а почему тут не из фикстуры? выглядит похоже на то, что рядом

2021-05-05 08:18 UTC, Mikhail-M commented on homework1/tests/test_data.py
> +def test_classifier(init_data, train_params):
чтобы шерить фикстуры между модулями conftest
https://habr.com/ru/post/448786/

2021-05-05 08:18 UTC, Mikhail-M commented on homework1/ml_project/data/prepare_data.py
> +def read_csv(path: str, **kwargs) -> pd.DataFrame:
давайте добавим логгер сюда

2021-05-05 15:58 UTC, akoshel commented on homework1/ml_project/data/prepare_data.py
> +def read_csv(path: str, **kwargs) -> pd.DataFrame:
пофиксил комменты с тестами и логгером

2021-05-06 07:47 UTC, Mikhail-M commented on homework1/ml_project/data/prepare_data.py
> +def read_csv(path: str, **kwargs) -> pd.DataFrame:
![image](https://user-images.githubusercontent.com/5405304/117261114-72b8c980-ae58-11eb-8bc4-1b52d6043b77.png)
нажимайте сюда, как будете готовы

2021-05-07 10:02 UTC, Mikhail-M approved these changes
Баллы: 31

2021-05-07 15:08 UTC, merged