Homework2
made-ml-in-prod-2021/akoshel pull request #3
Opened 2021-05-08 10:29 UTC by akoshel

Все это продублировано в Readme https://github.com/made-ml-in-prod-2021/akoshel/tree/homework2/online_inference
Идеи
Решил не оставлять результаты дз № 1, поэтому собрал это в пакет и использовал в дз № 2 В образ не передаю готовую предобученную модель, а подготавливаю ее там же при сборке докер образа. Каких-то конкретных целей это не приследует, просто хотел поэкспериментировать

Самоанализ
done +3
done +3
done +2
--
done +4
Посмотрел по ссылке, показалось что оптимально сделал. На ваше усмотрение :-) ?+3
done +2
done +1
done +1

Итого: 16(19)

2021-05-21 10:49 UTC, Mikhail-M requested changes
Жду ответов на вопросики, важно для дальнейшей проверки!

2021-05-21 10:49 UTC, Mikhail-M commented on homework1/Dockerfile
> +CMD ml_project_train configs/config_rf.yml train
Какую цель преследуют 2 cmd?

2021-05-21 10:49 UTC, Mikhail-M commented on online_inference/Dockerfile
> +RUN cd /homework1 && ml_project_train configs/config_rf.yml train
Можете описать достоинства и недостатки подхода, когда вы в докер контейнере для предикта учите модельку, если представить, что это не игрушечный пример?

2021-05-24 16:45 UTC, akoshel commented on homework1/Dockerfile
> +CMD ml_project_train configs/config_rf.yml train
Обучить модели из первой дз
Просто экспериментировал и решил оставить

2021-05-30 17:44 UTC, akoshel commented on online_inference/Dockerfile
> +RUN cd /homework1 && ml_project_train configs/config_rf.yml train
контейнер будет долго собираться
если надо будет сделать хотфикс и пересобрать контейнер будет вызывать проблемы
Другая сложность может быть примонтировать все источники с данными в кубер

2021-05-31 09:30 UTC, Mikhail-M commented on online_inference/Dockerfile
> +RUN cd /homework1 && ml_project_train configs/config_rf.yml train
Все -- так(насчет долго пересобираться, обучаться при старте, перед запускам инференса и тд)
про то как может быть организован процесс с обучением и выкаткой модели -- завтра на паре, а пока переделайте плз без этого=)

2021-05-31 16:54 UTC, akoshel commented on online_inference/Dockerfile
> +RUN cd /homework1 && ml_project_train configs/config_rf.yml train
пофиксил

2021-06-03 16:04 UTC, Mikhail-M approved these changes
Баллы: 17

2021-06-03 16:04 UTC, Mikhail-M commented on online_inference/Dockerfile
> +CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
а откуда внутри модель?

2021-06-03 16:17 UTC, akoshel commented on online_inference/Dockerfile
> +CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
COPY /homework1/models homework1/models

2021-06-03 16:17 UTC, merged