Homework3
made-ml-in-prod-2021/akoshel pull request #6
Opened 2021-06-11 11:12 UTC by akoshel

Самооценка

done +5
done +10
done +5
0
done +5
0
0
0
done +1

Total: 26

![1dag](https://user-images.githubusercontent.com/58721037/121677786-0c5e4100-cabf-11eb-8687-91c280310832.jpg)
![2dag](https://user-images.githubusercontent.com/58721037/121677810-12542200-cabf-11eb-93cc-b41e346a0c4a.jpg)
![3dag](https://user-images.githubusercontent.com/58721037/121677818-14b67c00-cabf-11eb-9a0e-4b1b309480cb.jpg)

2021-06-11 12:01 UTC, akoshel commented
https://disk.yandex.ru/d/AXKJMJJ1oSm93A
Папка data

2021-06-11 12:06 UTC, Illumaria commented
Привет!

А можно инструкцию по использованию? Пока воспроизвести не удалось:
![image](https://user-images.githubusercontent.com/47138294/121683721-7201fb80-cac6-11eb-8f32-bb1c0aa00385.png)

Тесты по команде `pytest` тоже не проходят.

2021-06-11 12:38 UTC, akoshel commented
Привет!
Добавил README https://github.com/made-ml-in-prod-2021/akoshel/blob/homework3/airflow_ml_dags/README.md
и полечил тесты

2021-06-11 14:03 UTC, Illumaria requested changes
И можно ещё пройтись по выводу `flake8`. Там немного, но плюс в карму точно будет. :)

2021-06-11 14:03 UTC, Illumaria commented on airflow_ml_dags/README.md
> +pip install -r requirement
Немного неполная строка. Некритично, но в глаза бросается. :)

2021-06-11 14:03 UTC, Illumaria commented on airflow_ml_dags/README.md
> +key: amazing_model_path, 	value=data/models/amazing_model
А зачем нужна эта переменная? Она в коде нигде не используется.

Предполагаю, что нужна она для дага `predict`, но дело в том, что этот даг отсутствует...

2021-06-11 14:03 UTC, Illumaria commented on airflow_ml_dags/dags/scripts/__init__.py
> +
Насколько я знаю, так обычно делают, чтобы запихать это всё в `__all__`? Либо в этом ините чего-то не хватает, либо, наоборот, всё лишнее, либо я не понимаю авторскую задумку.

2021-06-11 14:03 UTC, Illumaria commented on airflow_ml_dags/dags/03_validation.py
> +    validate
Ты же перенёс код валидации в `02_pipeline`, верно? Полагаю, этот файл целиком можно удалить.

2021-06-11 14:03 UTC, Illumaria commented on airflow_ml_dags/docker-compose.yml
> +  - AIRFLOW__CORE__LOAD_EXAMPLES=True
Можно выставить в `False`, чтобы убрать весь вот этот мусор...
![image](https://user-images.githubusercontent.com/47138294/121696151-703f3480-cad4-11eb-8ffe-b4dc19ab2169.png)

2021-06-11 14:03 UTC, Illumaria commented on airflow_ml_dags/images/airflow-docker/Dockerfile
> +RUN pip install ml_project-0.1.0.tar.gz
Вот ровно то же самое (`pip install ml_project-0.1.0.tar.gz`) нужно сделать, чтобы работали тесты. Лично мне такое решение не очень по душе, но судить не берусь. Дополни `README` и/или `requirements.txt`, пожалуйста.

2021-06-11 14:03 UTC, Illumaria commented on airflow_ml_dags/images/airflow-predict/predict.py
> +    data["predict"] = 1
Оригинально. :)

2021-06-11 14:03 UTC, Illumaria commented on airflow_ml_dags/requirements.txt
> +PyYAM==5.4.1
`PyYAML`, немножк опечатался.

2021-06-11 14:03 UTC, Illumaria commented on airflow_ml_dags/dags/02_pipeline.py
> +        start_date=airflow.utils.dates.days_ago(1),
Поставь здесь начальную дату "постарше", тогда не придётся дёргать даг ручками в админке.

Только сразу поделюсь мыслями: несмотря на то, что при `@weekly` даг должен запускаться в ночь с воскресенья на понедельник, у меня даже при значениях `days_ago`, равных 7-8, он почему-то не стартовал. Влепил 14 дней — запускается один раз 30 мая, но игнорирует 6 июня. Ну и чёрт с ним, главное, что запускается.

2021-06-13 14:56 UTC, akoshel commented on airflow_ml_dags/README.md
> +key: amazing_model_path, 	value=data/models/amazing_model
эта переменная нужна в 3-м ДАГе для применения нужной модели. В этой переменной нужно указать к ней путь

2021-06-13 14:57 UTC, akoshel commented on airflow_ml_dags/dags/scripts/__init__.py
> +
Я обычно делаю инит внутри модуля чтобы указать там всё что может уйти за пределы этого модуля.

2021-06-13 14:58 UTC, akoshel commented on airflow_ml_dags/dags/03_validation.py
> +    validate
Нет, валидация нужной моделью с получением предиктов в 3-м ДАГе, который заводится только в случае наличии переменной аэйрфлоу, о которой писал в readme.

2021-06-13 15:00 UTC, akoshel commented on airflow_ml_dags/images/airflow-docker/Dockerfile
> +RUN pip install ml_project-0.1.0.tar.gz
я его не внес в requirements. т.к. не выложил в pypi. Поэтому устанавливаю его так криво вручную подсовывая его.

2021-06-13 15:01 UTC, akoshel commented on airflow_ml_dags/images/airflow-predict/predict.py
> +    data["predict"] = 1
Это не мое, это из example c семинара, не удалил :)

2021-06-13 15:06 UTC, akoshel commented on airflow_ml_dags/dags/02_pipeline.py
> +        start_date=airflow.utils.dates.days_ago(1),
пофиксил. 
Спасибо за ревью! много пунктов указал, полезно обратить внимание
Сорян что моментами не так аккуратно, делал в сильной спешке

2021-06-14 14:11 UTC, Illumaria commented on airflow_ml_dags/images/airflow-docker/Dockerfile
> +RUN pip install ml_project-0.1.0.tar.gz
Да это понятно, я больше про то, что ты нигде об этом не написал. :) Из-за этого и тесты не работают из коробки.

2021-06-15 08:46 UTC, Illumaria approved these changes

2021-06-15 08:52 UTC, Illumaria commented
Больше вопросов нет. Код читается, всё понятно.

Единственное что — перестал работать `train`:
![image](https://user-images.githubusercontent.com/47138294/122022600-6b79c980-cdcf-11eb-8491-a7128a2bbcd7.png)
![image](https://user-images.githubusercontent.com/47138294/122022654-77658b80-cdcf-11eb-9f1a-9c5e3fee5f1c.png)
![image](https://user-images.githubusercontent.com/47138294/122022794-9c59fe80-cdcf-11eb-9548-2168bd56480d.png)

Не знаю, это я что-то испортил или же тут какая-то завязка на данные, что загружаются с Я.Диска, в то время как дагом генерируются неправильные.

В целом с поправкой на сроки с самооценкой согласен.

2021-06-19 11:38 UTC, akoshel commented
Привет
Спасибо за ревью!
hypothesis как-то криво генерит данные, не стал разбираться. Пофиксил, просто загружаю их по ссылке теперь
![image](https://user-images.githubusercontent.com/58721037/122641137-00e8c680-d10c-11eb-9909-5fbc46abe651.png)

2021-06-21 06:44 UTC, Mikhail-M approved these changes
Баллы: 26*0.6=15.6

2021-06-22 15:44 UTC, merged